/** Direrencia entre el serial y identity */
create TABLE
    users (user_id SERIAL PRIMARY KEY, username VARCHAR)
    -- Identity nos da mas control
create TABLE
    users2 (
        user_id INTEGER GENERATED by DEFAULT as IDENTITY PRIMARY KEY,
        username VARCHAR
    )
create TABLE
    users3 (
        user_id INTEGER GENERATED ALWAYS as IDENTITY PRIMARY KEY,
        username VARCHAR
    )
create TABLE
    users4 (
        user_id INTEGER GENERATED ALWAYS as IDENTITY (
            START WITH 100 INCREMENT BY 2
        ) PRIMARY KEY,
        username VARCHAR
    )